name: dev_summit_demo
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  arcgis_maps: ^200.6.0+4426

  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_web_auth_2: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/